name: Increment version

on:
  workflow_dispatch:
    inputs:
      increment-version:
        description: Increment semantic version
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  version-up:
    uses: snow-actions/.github/.github/workflows/increment-version.yml@main
    with:
      increment-version: ${{ github.event.inputs.increment-version }}
      secrets: inherit
