name: Notify pull request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            Pull request is opened.
            ${{ github.event.number }}: ${{ github.event.pull_request.title }}
            ${{ github.event.pull_request.html_url }}
